[package]
name = "ocicrypt-rs"
version = "0.1.0"
description = "the OCI image spec implementation of container image encryption"
repository = "https://github.com/containers/ocicrypt-rs"
readme = "README.md"
license = "Apache-2.0"
authors = ["The ocicrypt Authors"]
edition = "2024"

[dependencies]
anyhow.workspace = true
aes = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
base64.workspace = true
base64-serde = { workspace = true, optional = true }
ctr = { workspace = true, optional = true }
hmac = { workspace = true, optional = true }
josekit = { version = ">=0.7", optional = true }
openssl = { workspace = true, features = ["vendored"], optional = true }
pin-project-lite = { version = "0.2.17", optional = true }
protos = { path = "../protos", default-features = false, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2 = { workspace = true, optional = true }
tokio = { workspace = true, features = ["rt-multi-thread"], optional = true }
tonic = { workspace = true, optional = true }
tracing = { workspace = true }
ttrpc = { workspace = true, features = ["async"], optional = true }

[build-dependencies]

[dev-dependencies]
aes-gcm.workspace = true
ctrlc = { version = "3.5", features = ["termination"] }
hex.workspace = true
openssl = { workspace = true, features = ["vendored"] }
tokio = { workspace = true, features = ["time", "signal"] }

[features]
default = ["block-cipher", "keywrap-jwe", "keywrap-keyprovider-cmd"]

async-io = ["tokio"]

block-cipher = [
    "aes",
    "base64-serde",
    "ctr",
    "hmac",
    "openssl",
    "pin-project-lite",
    "sha2",
]

keywrap-jwe = ["josekit"]
keywrap-keyprovider = []
keywrap-keyprovider-cmd = ["keywrap-keyprovider"]
keywrap-keyprovider-grpc = [
    "keywrap-keyprovider",
    "tokio/net",
    "tonic",
    "protos/grpc",
]
keywrap-keyprovider-ttrpc = [
    "keywrap-keyprovider",
    "async-trait",
    "ttrpc",
    "tokio",
    "protos/ttrpc",
]
