name: 'Install Intel DCAP libraries'
inputs:
  ubuntu-version:
    required: true
runs:
  using: "composite"
  steps:
  - name: Install TDX dependencies
    id: install-tdx-dependencies
    shell: bash
    run: |
      curl -sL https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo gpg --dearmor --output /usr/share/keyrings/intel-sgx.gpg
      echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/intel-sgx.gpg] https://download.01.org/intel-sgx/sgx_repo/ubuntu ${{ inputs.ubuntu-version }} main' | sudo tee /etc/apt/sources.list.d/intel-sgx.list
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends libtdx-attest-dev
