// Copyright (c) 2025 Alibaba Cloud
//
// SPDX-License-Identifier: Apache-2.0
//

// grpc files generated by tonic_build are now formatted well
// so we need to skip rustfmt check for grpc files.
#[rustfmt::skip]
#[cfg(feature = "grpc")]
pub mod grpc;

#[cfg(feature = "ttrpc")]
pub mod ttrpc;
