// This file is generated by ttrpc-compiler 0.7.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
#![allow(clippy::all)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct GetResourceServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl GetResourceServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        GetResourceServiceClient {
            client,
        }
    }

    pub async fn get_resource(&self, ctx: ttrpc::context::Context, req: &super::getresource::GetResourceRequest) -> ::ttrpc::Result<super::getresource::GetResourceResponse> {
        let mut cres = super::getresource::GetResourceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "api.GetResourceService", "GetResource", cres);
    }
}

struct GetResourceMethod {
    service: Arc<dyn GetResourceService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for GetResourceMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, getresource, GetResourceRequest, get_resource);
    }
}

#[async_trait]
pub trait GetResourceService: Sync {
    async fn get_resource(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::getresource::GetResourceRequest) -> ::ttrpc::Result<super::getresource::GetResourceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/api.GetResourceService/GetResource is not supported".to_string())))
    }
}

pub fn create_get_resource_service(service: Arc<dyn GetResourceService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("GetResource".to_string(),
                    Box::new(GetResourceMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("api.GetResourceService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
