// Copyright (c) 2022 IBM
//
// SPDX-License-Identifier: Apache-2.0
//

use crate::InitDataResult;
use crate::utils::pad;

use super::tsm_report::*;
use super::{Attester, TeeEvidence};
use anyhow::*;
use serde::{Deserialize, Serialize};
use sev::firmware::guest::AttestationReport;
use sev::firmware::guest::Firmware;
use sev::firmware::host::CertTableEntry;
use std::path::Path;
use tracing::debug;

mod hostdata;

const SEV_GUEST_FALLBACK_DEVICE: &str = "/sys/devices/platform/sev-guest";

pub fn detect_platform() -> bool {
    TsmReportPath::new(TsmReportProvider::Sev).is_ok() || Path::new(SEV_GUEST_FALLBACK_DEVICE).exists()
}

#[derive(Serialize, Deserialize)]
struct SnpEvidence {
    attestation_report: AttestationReport,
    cert_chain: Option<Vec<CertTableEntry>>,
}

#[derive(Debug, Default)]
pub struct SnpAttester {   
    /// Linux TSM sysfs is used to read and write runtime measurement registers,
    /// and also read the registers like MRCONFIGID. This ability starts with kernel version 6.16.
    /// If the sysfs is not supported, the attester will use the the legacy path via the sev Rust crate, 
    /// which communicates with the kernel's /dev/sev-guest driver to get the report
    /// and the registers.
    supports_tsm_measurements: bool,
}

impl SnpAttester {
    pub fn new() -> Self {
        let supports_tsm_measurements = Path::new(TSM_REPORT_PATH).exists();
        if !supports_tsm_measurements {
            debug!("sysfs for SEV-SNP is not supported, which requires kernel version >= 6.16.");
        }

        Self {
            supports_tsm_measurements,
        }
    }
}

#[async_trait::async_trait]
impl Attester for SnpAttester {
    async fn get_evidence(&self, mut report_data: Vec<u8>) -> Result<TeeEvidence> {
        if report_data.len() > 64 {
            bail!("SNP Attester: Report data must be no more than 64 bytes");
        }

        report_data.resize(64, 0);

        // The VMPL value is set to 0, which means the report is generated at the highest privilege level.
        const VMPL: u8 = 0;

        // The attestation report generated by the SEV-SNP firmware, which includes the report data, measurement registers, and other information.
        let report: Vec<u8>;

        // The certificate chain generated by the SEV-SNP firmware, which includes the platform certificate, the CEK certificate, and the VCEK certificate.
        let certs: Option<Vec<CertTableEntry>>;

        if self.supports_tsm_measurements {
            // Use the TSM Report path to generate the attestation report and get the certificate chain.

            // Get and verify the TSM Report path instance for SEV-SNP.
            let tsm_report_path = TsmReportPath::new(TsmReportProvider::Sev)
                .context("SEV-SNP Attester: failed to create TSM Report path")?;

            // Generate the attestation report from the TSM Report path.
            report = tsm_report_path
                .attestation_report(TsmReportData::Sev(VMPL, report_data))?;

            // Get any available certificate chain data from the TSM Report path.
            let mut cert_table_data = tsm_report_path
                .supplemental_data()
                .context("SEV-SNP Attester: failed to get supplemental data")?;

            // Convert the certificate chain data from bytes to a vector of CertTableEntry structs and sort them.
            let mut certificates: Vec<CertTableEntry> = CertTableEntry::vec_bytes_to_cert_table(&mut cert_table_data)?;
            certificates.sort();

            // Set the certificate chain to None if it is empty, otherwise set it to Some(certificates).
            certs = match certificates.is_empty() { 
                true => None,
                false => Some(certificates) 
            }
        } else {
            // Use the legacy path via the sev Rust crate to generate the attestation report and get the certificate chain.
            let mut firmware = Firmware::open()?;
            let data = report_data.as_slice().try_into()?;
            (report, certs) = firmware
                .get_ext_report(None, Some(data), Some(VMPL as u32))
                .context("Failed to get attestation report")?;
        }

        let evidence = SnpEvidence {
            attestation_report: AttestationReport::from_bytes(&report)
                .context("Failed to parse attestation report")?,
            cert_chain: certs,
        };

        serde_json::to_value(&evidence).context("Serialize SNP evidence failed")
    }

    async fn bind_init_data(&self, init_data_digest: &[u8]) -> Result<InitDataResult> {
        let hostdata = hostdata::get_snp_host_data().context("Get HOSTDATA failed")?;
        let init_data: [u8; 32] = pad(init_data_digest);
        if init_data != hostdata {
            bail!("HOSTDATA does not match.");
        }

        Ok(InitDataResult::Ok)
    }
}
