// Copyright (c) 2022 IBM
//
// SPDX-License-Identifier: Apache-2.0
//

use crate::InitDataResult;
use crate::utils::pad;

use super::tsm_report::*;
use super::{Attester, TeeEvidence};
use anyhow::*;
use serde::{Deserialize, Serialize};
use sev::firmware::guest::AttestationReport;
use sev::firmware::guest::Firmware;
use sev::firmware::host::CertTableEntry;
use std::path::Path;
use tracing::{debug, error, warn};

mod hostdata;
pub mod vmpl;

pub use vmpl::{VMPrivilegeLevel, set_privlevel};

const SEV_GUEST_FALLBACK_DEVICE: &str = "/sys/devices/platform/sev-guest";

pub fn detect_platform() -> bool {
    TsmReportPath::new(TsmReportProvider::Sev).is_ok()
        || Path::new(SEV_GUEST_FALLBACK_DEVICE).exists()
}

#[derive(Serialize, Deserialize)]
struct SnpEvidence {
    attestation_report: AttestationReport,
    cert_chain: Option<Vec<CertTableEntry>>,
}

#[derive(Debug, Default)]
pub struct SnpAttester {}

#[async_trait::async_trait]
impl Attester for SnpAttester {
    async fn get_evidence(&self, mut report_data: Vec<u8>) -> Result<TeeEvidence> {
        if report_data.len() > 64 {
            bail!("SNP Attester: Report data must be no more than 64 bytes");
        }

        report_data.resize(64, 0);

        let (report, certs): (Vec<u8>, Option<Vec<CertTableEntry>>) =
            TsmReportPath::new(TsmReportProvider::Sev).map_or_else(
                |e| {
                    warn!("TSM Report not supported. Attestation report will be obtained via ioctl. Reason: {}", e);
                    // Use the legacy path via the sev Rust crate to generate the attestation report and get the certificate chain.
                    let mut firmware = Firmware::open()?;
                    let data = report_data.as_slice().try_into()?;
                    let (report, certs) = firmware
                        .get_ext_report(None, Some(data), Some(VMPrivilegeLevel::default() as u32))
                        .context("Failed to get attestation report")?;

                    Ok((report, certs))
                },
                |tsm|{
                    debug!("TSM Report for SEV-SNP is supported. The TSM Report path will be used.");

                    // Use the TSM Report path to generate the attestation report and get the certificate chain.

                    // Generate the attestation report from the TSM Report path.
                    // The attestation report generated by the SEV-SNP firmware, which includes the report data, measurement registers, and other information.
                    let report: Vec<u8> = set_privlevel(&tsm, VMPrivilegeLevel::default())?
                        .attestation_report(TsmReportData::Sev(report_data.clone()))?;

                    // Get any available certificate chain data from the TSM Report path.
                    // The certificate chain generated by the SEV-SNP firmware, which includes the platform certificate, the CEK certificate, and the VCEK certificate.
                    let mut cert_table_data = tsm
                        .supplemental_data()
                        .context("SEV-SNP Attester: failed to get supplemental data")?;

                    // Set the certificate chain to None if it is empty, otherwise set it to Some(certificates).
                    let certs = match cert_table_data.is_empty() {
                        true => None,
                        false => {
                            // Convert the certificate chain data from bytes to a vector of CertTableEntry structs and sort them.
                            let mut certificates: Vec<CertTableEntry> = CertTableEntry::vec_bytes_to_cert_table(&mut cert_table_data)
                                .map_err(|e| {
                                    error!("Failed to parse certificate table data: {:?}", e);
                                    e
                                })?;
                            certificates.sort();
                            Some(certificates)
                        }
                    };

                    Ok((report, certs))
                }
            )?;

        let evidence = SnpEvidence {
            attestation_report: AttestationReport::from_bytes(&report)
                .context("Failed to parse attestation report")?,
            cert_chain: certs,
        };

        serde_json::to_value(&evidence).context("Serialize SNP evidence failed")
    }

    async fn bind_init_data(&self, init_data_digest: &[u8]) -> Result<InitDataResult> {
        let hostdata = hostdata::get_snp_host_data().context("Get HOSTDATA failed")?;
        let init_data: [u8; 32] = pad(init_data_digest);
        if init_data != hostdata {
            bail!("HOSTDATA does not match.");
        }

        Ok(InitDataResult::Ok)
    }
}
