// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `api.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:api.UnsealSecretInput)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct UnsealSecretInput {
    // message fields
    // @@protoc_insertion_point(field:api.UnsealSecretInput.secret)
    pub secret: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:api.UnsealSecretInput.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a UnsealSecretInput {
    fn default() -> &'a UnsealSecretInput {
        <UnsealSecretInput as ::protobuf::Message>::default_instance()
    }
}

impl UnsealSecretInput {
    pub fn new() -> UnsealSecretInput {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "secret",
            |m: &UnsealSecretInput| { &m.secret },
            |m: &mut UnsealSecretInput| { &mut m.secret },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<UnsealSecretInput>(
            "UnsealSecretInput",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for UnsealSecretInput {
    const NAME: &'static str = "UnsealSecretInput";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.secret = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.secret.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.secret);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.secret.is_empty() {
            os.write_bytes(1, &self.secret)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> UnsealSecretInput {
        UnsealSecretInput::new()
    }

    fn clear(&mut self) {
        self.secret.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static UnsealSecretInput {
        static instance: UnsealSecretInput = UnsealSecretInput {
            secret: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for UnsealSecretInput {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("UnsealSecretInput").unwrap()).clone()
    }
}

impl ::std::fmt::Display for UnsealSecretInput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UnsealSecretInput {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:api.UnsealSecretOutput)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct UnsealSecretOutput {
    // message fields
    // @@protoc_insertion_point(field:api.UnsealSecretOutput.plaintext)
    pub plaintext: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:api.UnsealSecretOutput.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a UnsealSecretOutput {
    fn default() -> &'a UnsealSecretOutput {
        <UnsealSecretOutput as ::protobuf::Message>::default_instance()
    }
}

impl UnsealSecretOutput {
    pub fn new() -> UnsealSecretOutput {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "plaintext",
            |m: &UnsealSecretOutput| { &m.plaintext },
            |m: &mut UnsealSecretOutput| { &mut m.plaintext },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<UnsealSecretOutput>(
            "UnsealSecretOutput",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for UnsealSecretOutput {
    const NAME: &'static str = "UnsealSecretOutput";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.plaintext = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.plaintext.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.plaintext);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.plaintext.is_empty() {
            os.write_bytes(1, &self.plaintext)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> UnsealSecretOutput {
        UnsealSecretOutput::new()
    }

    fn clear(&mut self) {
        self.plaintext.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static UnsealSecretOutput {
        static instance: UnsealSecretOutput = UnsealSecretOutput {
            plaintext: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for UnsealSecretOutput {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("UnsealSecretOutput").unwrap()).clone()
    }
}

impl ::std::fmt::Display for UnsealSecretOutput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UnsealSecretOutput {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:api.GetResourceRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetResourceRequest {
    // message fields
    // @@protoc_insertion_point(field:api.GetResourceRequest.ResourcePath)
    pub ResourcePath: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:api.GetResourceRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetResourceRequest {
    fn default() -> &'a GetResourceRequest {
        <GetResourceRequest as ::protobuf::Message>::default_instance()
    }
}

impl GetResourceRequest {
    pub fn new() -> GetResourceRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ResourcePath",
            |m: &GetResourceRequest| { &m.ResourcePath },
            |m: &mut GetResourceRequest| { &mut m.ResourcePath },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetResourceRequest>(
            "GetResourceRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetResourceRequest {
    const NAME: &'static str = "GetResourceRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.ResourcePath = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.ResourcePath.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.ResourcePath);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.ResourcePath.is_empty() {
            os.write_string(1, &self.ResourcePath)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetResourceRequest {
        GetResourceRequest::new()
    }

    fn clear(&mut self) {
        self.ResourcePath.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetResourceRequest {
        static instance: GetResourceRequest = GetResourceRequest {
            ResourcePath: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetResourceRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetResourceRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetResourceRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetResourceRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:api.GetResourceResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetResourceResponse {
    // message fields
    // @@protoc_insertion_point(field:api.GetResourceResponse.Resource)
    pub Resource: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:api.GetResourceResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetResourceResponse {
    fn default() -> &'a GetResourceResponse {
        <GetResourceResponse as ::protobuf::Message>::default_instance()
    }
}

impl GetResourceResponse {
    pub fn new() -> GetResourceResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "Resource",
            |m: &GetResourceResponse| { &m.Resource },
            |m: &mut GetResourceResponse| { &mut m.Resource },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetResourceResponse>(
            "GetResourceResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetResourceResponse {
    const NAME: &'static str = "GetResourceResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.Resource = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.Resource.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.Resource);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.Resource.is_empty() {
            os.write_bytes(1, &self.Resource)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetResourceResponse {
        GetResourceResponse::new()
    }

    fn clear(&mut self) {
        self.Resource.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetResourceResponse {
        static instance: GetResourceResponse = GetResourceResponse {
            Resource: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetResourceResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetResourceResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetResourceResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetResourceResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:api.SecureMountRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SecureMountRequest {
    // message fields
    // @@protoc_insertion_point(field:api.SecureMountRequest.volume_type)
    pub volume_type: ::std::string::String,
    // @@protoc_insertion_point(field:api.SecureMountRequest.options)
    pub options: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    // @@protoc_insertion_point(field:api.SecureMountRequest.flags)
    pub flags: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:api.SecureMountRequest.mount_point)
    pub mount_point: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:api.SecureMountRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SecureMountRequest {
    fn default() -> &'a SecureMountRequest {
        <SecureMountRequest as ::protobuf::Message>::default_instance()
    }
}

impl SecureMountRequest {
    pub fn new() -> SecureMountRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "volume_type",
            |m: &SecureMountRequest| { &m.volume_type },
            |m: &mut SecureMountRequest| { &mut m.volume_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor_new::<_, _>(
            "options",
            |m: &SecureMountRequest| { &m.options },
            |m: &mut SecureMountRequest| { &mut m.options },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "flags",
            |m: &SecureMountRequest| { &m.flags },
            |m: &mut SecureMountRequest| { &mut m.flags },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "mount_point",
            |m: &SecureMountRequest| { &m.mount_point },
            |m: &mut SecureMountRequest| { &mut m.mount_point },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SecureMountRequest>(
            "SecureMountRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SecureMountRequest {
    const NAME: &'static str = "SecureMountRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.volume_type = is.read_string()?;
                },
                18 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            10 => key = is.read_string()?,
                            18 => value = is.read_string()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.options.insert(key, value);
                },
                26 => {
                    self.flags.push(is.read_string()?);
                },
                34 => {
                    self.mount_point = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.volume_type.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.volume_type);
        }
        for (k, v) in &self.options {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::string_size(2, &v);
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        for value in &self.flags {
            my_size += ::protobuf::rt::string_size(3, &value);
        };
        if !self.mount_point.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.mount_point);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.volume_type.is_empty() {
            os.write_string(1, &self.volume_type)?;
        }
        for (k, v) in &self.options {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::string_size(2, &v);
            os.write_raw_varint32(18)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_string(1, &k)?;
            os.write_string(2, &v)?;
        };
        for v in &self.flags {
            os.write_string(3, &v)?;
        };
        if !self.mount_point.is_empty() {
            os.write_string(4, &self.mount_point)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SecureMountRequest {
        SecureMountRequest::new()
    }

    fn clear(&mut self) {
        self.volume_type.clear();
        self.options.clear();
        self.flags.clear();
        self.mount_point.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SecureMountRequest {
        static instance: ::protobuf::rt::Lazy<SecureMountRequest> = ::protobuf::rt::Lazy::new();
        instance.get(SecureMountRequest::new)
    }
}

impl ::protobuf::MessageFull for SecureMountRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SecureMountRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SecureMountRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SecureMountRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:api.SecureMountResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SecureMountResponse {
    // special fields
    // @@protoc_insertion_point(special_field:api.SecureMountResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SecureMountResponse {
    fn default() -> &'a SecureMountResponse {
        <SecureMountResponse as ::protobuf::Message>::default_instance()
    }
}

impl SecureMountResponse {
    pub fn new() -> SecureMountResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SecureMountResponse>(
            "SecureMountResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SecureMountResponse {
    const NAME: &'static str = "SecureMountResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SecureMountResponse {
        SecureMountResponse::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SecureMountResponse {
        static instance: SecureMountResponse = SecureMountResponse {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SecureMountResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SecureMountResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SecureMountResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SecureMountResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:api.ImagePullRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ImagePullRequest {
    // message fields
    // @@protoc_insertion_point(field:api.ImagePullRequest.image_url)
    pub image_url: ::std::string::String,
    // @@protoc_insertion_point(field:api.ImagePullRequest.bundle_path)
    pub bundle_path: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:api.ImagePullRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ImagePullRequest {
    fn default() -> &'a ImagePullRequest {
        <ImagePullRequest as ::protobuf::Message>::default_instance()
    }
}

impl ImagePullRequest {
    pub fn new() -> ImagePullRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "image_url",
            |m: &ImagePullRequest| { &m.image_url },
            |m: &mut ImagePullRequest| { &mut m.image_url },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "bundle_path",
            |m: &ImagePullRequest| { &m.bundle_path },
            |m: &mut ImagePullRequest| { &mut m.bundle_path },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ImagePullRequest>(
            "ImagePullRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ImagePullRequest {
    const NAME: &'static str = "ImagePullRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.image_url = is.read_string()?;
                },
                18 => {
                    self.bundle_path = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.image_url.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.image_url);
        }
        if !self.bundle_path.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.bundle_path);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.image_url.is_empty() {
            os.write_string(1, &self.image_url)?;
        }
        if !self.bundle_path.is_empty() {
            os.write_string(2, &self.bundle_path)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ImagePullRequest {
        ImagePullRequest::new()
    }

    fn clear(&mut self) {
        self.image_url.clear();
        self.bundle_path.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ImagePullRequest {
        static instance: ImagePullRequest = ImagePullRequest {
            image_url: ::std::string::String::new(),
            bundle_path: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ImagePullRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ImagePullRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ImagePullRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ImagePullRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:api.ImagePullResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ImagePullResponse {
    // message fields
    // @@protoc_insertion_point(field:api.ImagePullResponse.manifest_digest)
    pub manifest_digest: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:api.ImagePullResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ImagePullResponse {
    fn default() -> &'a ImagePullResponse {
        <ImagePullResponse as ::protobuf::Message>::default_instance()
    }
}

impl ImagePullResponse {
    pub fn new() -> ImagePullResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "manifest_digest",
            |m: &ImagePullResponse| { &m.manifest_digest },
            |m: &mut ImagePullResponse| { &mut m.manifest_digest },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ImagePullResponse>(
            "ImagePullResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ImagePullResponse {
    const NAME: &'static str = "ImagePullResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.manifest_digest = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.manifest_digest.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.manifest_digest);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.manifest_digest.is_empty() {
            os.write_string(1, &self.manifest_digest)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ImagePullResponse {
        ImagePullResponse::new()
    }

    fn clear(&mut self) {
        self.manifest_digest.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ImagePullResponse {
        static instance: ImagePullResponse = ImagePullResponse {
            manifest_digest: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ImagePullResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ImagePullResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ImagePullResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ImagePullResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\tapi.proto\x12\x03api\"+\n\x11UnsealSecretInput\x12\x16\n\x06secret\
    \x18\x01\x20\x01(\x0cR\x06secret\"2\n\x12UnsealSecretOutput\x12\x1c\n\tp\
    laintext\x18\x01\x20\x01(\x0cR\tplaintext\"8\n\x12GetResourceRequest\x12\
    \"\n\x0cResourcePath\x18\x01\x20\x01(\tR\x0cResourcePath\"1\n\x13GetReso\
    urceResponse\x12\x1a\n\x08Resource\x18\x01\x20\x01(\x0cR\x08Resource\"\
    \xe8\x01\n\x12SecureMountRequest\x12\x1f\n\x0bvolume_type\x18\x01\x20\
    \x01(\tR\nvolumeType\x12>\n\x07options\x18\x02\x20\x03(\x0b2$.api.Secure\
    MountRequest.OptionsEntryR\x07options\x12\x14\n\x05flags\x18\x03\x20\x03\
    (\tR\x05flags\x12\x1f\n\x0bmount_point\x18\x04\x20\x01(\tR\nmountPoint\
    \x1a:\n\x0cOptionsEntry\x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12\
    \x14\n\x05value\x18\x02\x20\x01(\tR\x05value:\x028\x01\"\x15\n\x13Secure\
    MountResponse\"P\n\x10ImagePullRequest\x12\x1b\n\timage_url\x18\x01\x20\
    \x01(\tR\x08imageUrl\x12\x1f\n\x0bbundle_path\x18\x02\x20\x01(\tR\nbundl\
    ePath\"<\n\x11ImagePullResponse\x12'\n\x0fmanifest_digest\x18\x01\x20\
    \x01(\tR\x0emanifestDigest2V\n\x13SealedSecretService\x12?\n\x0cUnsealSe\
    cret\x12\x16.api.UnsealSecretInput\x1a\x17.api.UnsealSecretOutput2V\n\
    \x12GetResourceService\x12@\n\x0bGetResource\x12\x17.api.GetResourceRequ\
    est\x1a\x18.api.GetResourceResponse2V\n\x12SecureMountService\x12@\n\x0b\
    SecureMount\x12\x17.api.SecureMountRequest\x1a\x18.api.SecureMountRespon\
    se2N\n\x10ImagePullService\x12:\n\tPullImage\x12\x15.api.ImagePullReques\
    t\x1a\x16.api.ImagePullResponseb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(8);
            messages.push(UnsealSecretInput::generated_message_descriptor_data());
            messages.push(UnsealSecretOutput::generated_message_descriptor_data());
            messages.push(GetResourceRequest::generated_message_descriptor_data());
            messages.push(GetResourceResponse::generated_message_descriptor_data());
            messages.push(SecureMountRequest::generated_message_descriptor_data());
            messages.push(SecureMountResponse::generated_message_descriptor_data());
            messages.push(ImagePullRequest::generated_message_descriptor_data());
            messages.push(ImagePullResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
