// This file is generated by rust-protobuf 3.5.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `attestation-agent.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_5_0;

// @@protoc_insertion_point(message:attestation_agent.GetEvidenceRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetEvidenceRequest {
    // message fields
    // @@protoc_insertion_point(field:attestation_agent.GetEvidenceRequest.RuntimeData)
    pub RuntimeData: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.GetEvidenceRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetEvidenceRequest {
    fn default() -> &'a GetEvidenceRequest {
        <GetEvidenceRequest as ::protobuf::Message>::default_instance()
    }
}

impl GetEvidenceRequest {
    pub fn new() -> GetEvidenceRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "RuntimeData",
            |m: &GetEvidenceRequest| { &m.RuntimeData },
            |m: &mut GetEvidenceRequest| { &mut m.RuntimeData },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetEvidenceRequest>(
            "GetEvidenceRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetEvidenceRequest {
    const NAME: &'static str = "GetEvidenceRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.RuntimeData = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.RuntimeData.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.RuntimeData);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.RuntimeData.is_empty() {
            os.write_bytes(1, &self.RuntimeData)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetEvidenceRequest {
        GetEvidenceRequest::new()
    }

    fn clear(&mut self) {
        self.RuntimeData.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetEvidenceRequest {
        static instance: GetEvidenceRequest = GetEvidenceRequest {
            RuntimeData: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetEvidenceRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetEvidenceRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetEvidenceRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetEvidenceRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation_agent.GetEvidenceResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetEvidenceResponse {
    // message fields
    // @@protoc_insertion_point(field:attestation_agent.GetEvidenceResponse.Evidence)
    pub Evidence: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.GetEvidenceResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetEvidenceResponse {
    fn default() -> &'a GetEvidenceResponse {
        <GetEvidenceResponse as ::protobuf::Message>::default_instance()
    }
}

impl GetEvidenceResponse {
    pub fn new() -> GetEvidenceResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "Evidence",
            |m: &GetEvidenceResponse| { &m.Evidence },
            |m: &mut GetEvidenceResponse| { &mut m.Evidence },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetEvidenceResponse>(
            "GetEvidenceResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetEvidenceResponse {
    const NAME: &'static str = "GetEvidenceResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.Evidence = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.Evidence.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.Evidence);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.Evidence.is_empty() {
            os.write_bytes(1, &self.Evidence)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetEvidenceResponse {
        GetEvidenceResponse::new()
    }

    fn clear(&mut self) {
        self.Evidence.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetEvidenceResponse {
        static instance: GetEvidenceResponse = GetEvidenceResponse {
            Evidence: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetEvidenceResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetEvidenceResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetEvidenceResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetEvidenceResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation_agent.GetTokenRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetTokenRequest {
    // message fields
    // @@protoc_insertion_point(field:attestation_agent.GetTokenRequest.TokenType)
    pub TokenType: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.GetTokenRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetTokenRequest {
    fn default() -> &'a GetTokenRequest {
        <GetTokenRequest as ::protobuf::Message>::default_instance()
    }
}

impl GetTokenRequest {
    pub fn new() -> GetTokenRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "TokenType",
            |m: &GetTokenRequest| { &m.TokenType },
            |m: &mut GetTokenRequest| { &mut m.TokenType },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetTokenRequest>(
            "GetTokenRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetTokenRequest {
    const NAME: &'static str = "GetTokenRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.TokenType = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.TokenType.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.TokenType);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.TokenType.is_empty() {
            os.write_string(1, &self.TokenType)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetTokenRequest {
        GetTokenRequest::new()
    }

    fn clear(&mut self) {
        self.TokenType.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetTokenRequest {
        static instance: GetTokenRequest = GetTokenRequest {
            TokenType: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetTokenRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetTokenRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetTokenRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetTokenRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation_agent.GetTokenResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetTokenResponse {
    // message fields
    // @@protoc_insertion_point(field:attestation_agent.GetTokenResponse.Token)
    pub Token: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.GetTokenResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetTokenResponse {
    fn default() -> &'a GetTokenResponse {
        <GetTokenResponse as ::protobuf::Message>::default_instance()
    }
}

impl GetTokenResponse {
    pub fn new() -> GetTokenResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "Token",
            |m: &GetTokenResponse| { &m.Token },
            |m: &mut GetTokenResponse| { &mut m.Token },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetTokenResponse>(
            "GetTokenResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetTokenResponse {
    const NAME: &'static str = "GetTokenResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.Token = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.Token.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.Token);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.Token.is_empty() {
            os.write_bytes(1, &self.Token)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetTokenResponse {
        GetTokenResponse::new()
    }

    fn clear(&mut self) {
        self.Token.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetTokenResponse {
        static instance: GetTokenResponse = GetTokenResponse {
            Token: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetTokenResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetTokenResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetTokenResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetTokenResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation_agent.ExtendRuntimeMeasurementRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ExtendRuntimeMeasurementRequest {
    // message fields
    // @@protoc_insertion_point(field:attestation_agent.ExtendRuntimeMeasurementRequest.Events)
    pub Events: ::std::vec::Vec<::std::vec::Vec<u8>>,
    // @@protoc_insertion_point(field:attestation_agent.ExtendRuntimeMeasurementRequest.RegisterIndex)
    pub RegisterIndex: ::std::option::Option<u64>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.ExtendRuntimeMeasurementRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ExtendRuntimeMeasurementRequest {
    fn default() -> &'a ExtendRuntimeMeasurementRequest {
        <ExtendRuntimeMeasurementRequest as ::protobuf::Message>::default_instance()
    }
}

impl ExtendRuntimeMeasurementRequest {
    pub fn new() -> ExtendRuntimeMeasurementRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "Events",
            |m: &ExtendRuntimeMeasurementRequest| { &m.Events },
            |m: &mut ExtendRuntimeMeasurementRequest| { &mut m.Events },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "RegisterIndex",
            |m: &ExtendRuntimeMeasurementRequest| { &m.RegisterIndex },
            |m: &mut ExtendRuntimeMeasurementRequest| { &mut m.RegisterIndex },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ExtendRuntimeMeasurementRequest>(
            "ExtendRuntimeMeasurementRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ExtendRuntimeMeasurementRequest {
    const NAME: &'static str = "ExtendRuntimeMeasurementRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.Events.push(is.read_bytes()?);
                },
                16 => {
                    self.RegisterIndex = ::std::option::Option::Some(is.read_uint64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.Events {
            my_size += ::protobuf::rt::bytes_size(1, &value);
        };
        if let Some(v) = self.RegisterIndex {
            my_size += ::protobuf::rt::uint64_size(2, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.Events {
            os.write_bytes(1, &v)?;
        };
        if let Some(v) = self.RegisterIndex {
            os.write_uint64(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ExtendRuntimeMeasurementRequest {
        ExtendRuntimeMeasurementRequest::new()
    }

    fn clear(&mut self) {
        self.Events.clear();
        self.RegisterIndex = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ExtendRuntimeMeasurementRequest {
        static instance: ExtendRuntimeMeasurementRequest = ExtendRuntimeMeasurementRequest {
            Events: ::std::vec::Vec::new(),
            RegisterIndex: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ExtendRuntimeMeasurementRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ExtendRuntimeMeasurementRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ExtendRuntimeMeasurementRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ExtendRuntimeMeasurementRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation_agent.ExtendRuntimeMeasurementResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ExtendRuntimeMeasurementResponse {
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.ExtendRuntimeMeasurementResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ExtendRuntimeMeasurementResponse {
    fn default() -> &'a ExtendRuntimeMeasurementResponse {
        <ExtendRuntimeMeasurementResponse as ::protobuf::Message>::default_instance()
    }
}

impl ExtendRuntimeMeasurementResponse {
    pub fn new() -> ExtendRuntimeMeasurementResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ExtendRuntimeMeasurementResponse>(
            "ExtendRuntimeMeasurementResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ExtendRuntimeMeasurementResponse {
    const NAME: &'static str = "ExtendRuntimeMeasurementResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ExtendRuntimeMeasurementResponse {
        ExtendRuntimeMeasurementResponse::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ExtendRuntimeMeasurementResponse {
        static instance: ExtendRuntimeMeasurementResponse = ExtendRuntimeMeasurementResponse {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ExtendRuntimeMeasurementResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ExtendRuntimeMeasurementResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ExtendRuntimeMeasurementResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ExtendRuntimeMeasurementResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation_agent.InitDataPlaintext)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct InitDataPlaintext {
    // message fields
    // @@protoc_insertion_point(field:attestation_agent.InitDataPlaintext.Content)
    pub Content: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:attestation_agent.InitDataPlaintext.Algorithm)
    pub Algorithm: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.InitDataPlaintext.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a InitDataPlaintext {
    fn default() -> &'a InitDataPlaintext {
        <InitDataPlaintext as ::protobuf::Message>::default_instance()
    }
}

impl InitDataPlaintext {
    pub fn new() -> InitDataPlaintext {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "Content",
            |m: &InitDataPlaintext| { &m.Content },
            |m: &mut InitDataPlaintext| { &mut m.Content },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "Algorithm",
            |m: &InitDataPlaintext| { &m.Algorithm },
            |m: &mut InitDataPlaintext| { &mut m.Algorithm },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<InitDataPlaintext>(
            "InitDataPlaintext",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for InitDataPlaintext {
    const NAME: &'static str = "InitDataPlaintext";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.Content = is.read_bytes()?;
                },
                18 => {
                    self.Algorithm = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.Content.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.Content);
        }
        if !self.Algorithm.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.Algorithm);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.Content.is_empty() {
            os.write_bytes(1, &self.Content)?;
        }
        if !self.Algorithm.is_empty() {
            os.write_string(2, &self.Algorithm)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> InitDataPlaintext {
        InitDataPlaintext::new()
    }

    fn clear(&mut self) {
        self.Content.clear();
        self.Algorithm.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static InitDataPlaintext {
        static instance: InitDataPlaintext = InitDataPlaintext {
            Content: ::std::vec::Vec::new(),
            Algorithm: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for InitDataPlaintext {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("InitDataPlaintext").unwrap()).clone()
    }
}

impl ::std::fmt::Display for InitDataPlaintext {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for InitDataPlaintext {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation_agent.CheckInitDataRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CheckInitDataRequest {
    // message fields
    // @@protoc_insertion_point(field:attestation_agent.CheckInitDataRequest.Digest)
    pub Digest: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.CheckInitDataRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CheckInitDataRequest {
    fn default() -> &'a CheckInitDataRequest {
        <CheckInitDataRequest as ::protobuf::Message>::default_instance()
    }
}

impl CheckInitDataRequest {
    pub fn new() -> CheckInitDataRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "Digest",
            |m: &CheckInitDataRequest| { &m.Digest },
            |m: &mut CheckInitDataRequest| { &mut m.Digest },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CheckInitDataRequest>(
            "CheckInitDataRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CheckInitDataRequest {
    const NAME: &'static str = "CheckInitDataRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.Digest = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.Digest.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.Digest);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.Digest.is_empty() {
            os.write_bytes(1, &self.Digest)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CheckInitDataRequest {
        CheckInitDataRequest::new()
    }

    fn clear(&mut self) {
        self.Digest.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CheckInitDataRequest {
        static instance: CheckInitDataRequest = CheckInitDataRequest {
            Digest: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CheckInitDataRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CheckInitDataRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CheckInitDataRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CheckInitDataRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation_agent.CheckInitDataResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CheckInitDataResponse {
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.CheckInitDataResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CheckInitDataResponse {
    fn default() -> &'a CheckInitDataResponse {
        <CheckInitDataResponse as ::protobuf::Message>::default_instance()
    }
}

impl CheckInitDataResponse {
    pub fn new() -> CheckInitDataResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CheckInitDataResponse>(
            "CheckInitDataResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CheckInitDataResponse {
    const NAME: &'static str = "CheckInitDataResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CheckInitDataResponse {
        CheckInitDataResponse::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CheckInitDataResponse {
        static instance: CheckInitDataResponse = CheckInitDataResponse {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CheckInitDataResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CheckInitDataResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CheckInitDataResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CheckInitDataResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation_agent.UpdateConfigurationRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct UpdateConfigurationRequest {
    // message fields
    // @@protoc_insertion_point(field:attestation_agent.UpdateConfigurationRequest.config)
    pub config: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.UpdateConfigurationRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a UpdateConfigurationRequest {
    fn default() -> &'a UpdateConfigurationRequest {
        <UpdateConfigurationRequest as ::protobuf::Message>::default_instance()
    }
}

impl UpdateConfigurationRequest {
    pub fn new() -> UpdateConfigurationRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "config",
            |m: &UpdateConfigurationRequest| { &m.config },
            |m: &mut UpdateConfigurationRequest| { &mut m.config },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<UpdateConfigurationRequest>(
            "UpdateConfigurationRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for UpdateConfigurationRequest {
    const NAME: &'static str = "UpdateConfigurationRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.config = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.config.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.config);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.config.is_empty() {
            os.write_string(1, &self.config)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> UpdateConfigurationRequest {
        UpdateConfigurationRequest::new()
    }

    fn clear(&mut self) {
        self.config.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static UpdateConfigurationRequest {
        static instance: UpdateConfigurationRequest = UpdateConfigurationRequest {
            config: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for UpdateConfigurationRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("UpdateConfigurationRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for UpdateConfigurationRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UpdateConfigurationRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation_agent.UpdateConfigurationResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct UpdateConfigurationResponse {
    // special fields
    // @@protoc_insertion_point(special_field:attestation_agent.UpdateConfigurationResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a UpdateConfigurationResponse {
    fn default() -> &'a UpdateConfigurationResponse {
        <UpdateConfigurationResponse as ::protobuf::Message>::default_instance()
    }
}

impl UpdateConfigurationResponse {
    pub fn new() -> UpdateConfigurationResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<UpdateConfigurationResponse>(
            "UpdateConfigurationResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for UpdateConfigurationResponse {
    const NAME: &'static str = "UpdateConfigurationResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> UpdateConfigurationResponse {
        UpdateConfigurationResponse::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static UpdateConfigurationResponse {
        static instance: UpdateConfigurationResponse = UpdateConfigurationResponse {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for UpdateConfigurationResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("UpdateConfigurationResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for UpdateConfigurationResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UpdateConfigurationResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x17attestation-agent.proto\x12\x11attestation_agent\"6\n\x12GetEviden\
    ceRequest\x12\x20\n\x0bRuntimeData\x18\x01\x20\x01(\x0cR\x0bRuntimeData\
    \"1\n\x13GetEvidenceResponse\x12\x1a\n\x08Evidence\x18\x01\x20\x01(\x0cR\
    \x08Evidence\"/\n\x0fGetTokenRequest\x12\x1c\n\tTokenType\x18\x01\x20\
    \x01(\tR\tTokenType\"(\n\x10GetTokenResponse\x12\x14\n\x05Token\x18\x01\
    \x20\x01(\x0cR\x05Token\"v\n\x1fExtendRuntimeMeasurementRequest\x12\x16\
    \n\x06Events\x18\x01\x20\x03(\x0cR\x06Events\x12)\n\rRegisterIndex\x18\
    \x02\x20\x01(\x04H\0R\rRegisterIndex\x88\x01\x01B\x10\n\x0e_RegisterInde\
    x\"\"\n\x20ExtendRuntimeMeasurementResponse\"K\n\x11InitDataPlaintext\
    \x12\x18\n\x07Content\x18\x01\x20\x01(\x0cR\x07Content\x12\x1c\n\tAlgori\
    thm\x18\x02\x20\x01(\tR\tAlgorithm\".\n\x14CheckInitDataRequest\x12\x16\
    \n\x06Digest\x18\x01\x20\x01(\x0cR\x06Digest\"\x17\n\x15CheckInitDataRes\
    ponse\"4\n\x1aUpdateConfigurationRequest\x12\x16\n\x06config\x18\x01\x20\
    \x01(\tR\x06config\"\x1d\n\x1bUpdateConfigurationResponse2\xac\x04\n\x17\
    AttestationAgentService\x12\\\n\x0bGetEvidence\x12%.attestation_agent.Ge\
    tEvidenceRequest\x1a&.attestation_agent.GetEvidenceResponse\x12S\n\x08Ge\
    tToken\x12\".attestation_agent.GetTokenRequest\x1a#.attestation_agent.Ge\
    tTokenResponse\x12\x83\x01\n\x18ExtendRuntimeMeasurement\x122.attestatio\
    n_agent.ExtendRuntimeMeasurementRequest\x1a3.attestation_agent.ExtendRun\
    timeMeasurementResponse\x12b\n\rCheckInitData\x12'.attestation_agent.Che\
    ckInitDataRequest\x1a(.attestation_agent.CheckInitDataResponse\x12t\n\
    \x13UpdateConfiguration\x12-.attestation_agent.UpdateConfigurationReques\
    t\x1a..attestation_agent.UpdateConfigurationResponseb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(11);
            messages.push(GetEvidenceRequest::generated_message_descriptor_data());
            messages.push(GetEvidenceResponse::generated_message_descriptor_data());
            messages.push(GetTokenRequest::generated_message_descriptor_data());
            messages.push(GetTokenResponse::generated_message_descriptor_data());
            messages.push(ExtendRuntimeMeasurementRequest::generated_message_descriptor_data());
            messages.push(ExtendRuntimeMeasurementResponse::generated_message_descriptor_data());
            messages.push(InitDataPlaintext::generated_message_descriptor_data());
            messages.push(CheckInitDataRequest::generated_message_descriptor_data());
            messages.push(CheckInitDataResponse::generated_message_descriptor_data());
            messages.push(UpdateConfigurationRequest::generated_message_descriptor_data());
            messages.push(UpdateConfigurationResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
