[package]
name = "signature"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
strum = { version = "0.23.0", features = ["derive"] }
url = "2.2.2"
anyhow = "1.0"
oci-distribution = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"