name: attestation-agent basic build and unit tests

on:
  push:
    branches:
      - "main"
    paths:
      - 'attestation-agent/**'
      - '.github/workflows/aa_basic.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - 'attestation-agent/**'
      - '.github/workflows/aa_basic.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'
  create:
  workflow_dispatch:

jobs:
  basic_ci:
    name: Check
    defaults:
      run:
        working-directory: ./attestation-agent
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Install protoc
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install TDX dependencies
        run: |
          sudo curl -sL https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo gpg --dearmor --output /usr/share/keyrings/intel-sgx.gpg
          sudo echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/intel-sgx.gpg] https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy main' | sudo tee /etc/apt/sources.list.d/intel-sgx.list
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libtdx-attest-dev

      - name: Install TPM dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtss2-dev

      - name: Install dm-verity dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdevmapper-dev

      - name: Gnu build and install with ttrpc
        run: |
          make ttrpc=true && make install

      - name: Musl build with all platform
        run: |
          make LIBC=musl ttrpc=true ATTESTER=none

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features openssl,rust-crypto,all-attesters,kbs,coco_as -p attestation-agent -p attester -p coco_keyprovider -p kbc -p kbs_protocol -p crypto -p resource_uri

      - name: Run cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run rust lint check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # We are getting error in generated code due to derive_partial_eq_without_eq check, so ignore it for now
          args: --workspace -- -D warnings -A clippy::derive-partial-eq-without-eq
