name: attestation-agent coco_keyprovider tests
on:
  push:
    branches:
      - 'main'
    paths:
      - 'attestation-agent/coco_keyprovider/**'
      - '.github/workflows/aa_sample_keyprovider.yml'
  pull_request:
    paths:
      - 'attestation-agent/coco_keyprovider/**'
      - '.github/workflows/aa_sample_keyprovider.yml'
  create:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  coco_keyprovider_ci:
    permissions:
      contents: read
    if: github.event_name != 'push'
    name: Check
    strategy:
      fail-fast: false
      matrix:
        instance:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.instance }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Code checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          components: rustfmt, clippy

      - name: Rust fmt check
        run: cargo fmt --check --manifest-path attestation-agent/coco_keyprovider/Cargo.toml

      - name: Rust clippy check
        run: cargo clippy --manifest-path attestation-agent/coco_keyprovider/Cargo.toml -- -D warnings

      - name: Build and install
        run: cargo build --manifest-path attestation-agent/coco_keyprovider/Cargo.toml

      - name: Run cargo test
        run: cargo test --manifest-path attestation-agent/coco_keyprovider/Cargo.toml
