name: check links

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checklinks:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      #  TODO: fix this workflow
      # - name: Restore lychee cache
      #   uses: actions/cache@v4
      #   with:
      #     path: .lycheecache
      #     key: cache-lychee-${{ github.sha }}
      #     restore-keys: cache-lychee-

      # - name: Check links
      #   uses: lycheeverse/lychee-action@v2
      #   with:
      #     args: "--cache --max-cache-age 1d ."
      #     fail: true
