name: check links

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checklinks:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      #  TODO: fix this workflow
      # - name: Restore lychee cache
      #   uses: actions/cache@v4
      #   with:
      #     path: .lycheecache
      #     key: cache-lychee-${{ github.sha }}
      #     restore-keys: cache-lychee-

      # - name: Check links
      #   uses: lycheeverse/lychee-action@v2
      #   with:
      #     args: "--cache --max-cache-age 1d ."
      #     fail: true
