name: check links

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checklinks:
    name: Check links
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      #  TODO: fix this workflow
      # - name: Restore lychee cache
      #   uses: actions/cache@v4
      #   with:
      #     path: .lycheecache
      #     key: cache-lychee-${{ github.sha }}
      #     restore-keys: cache-lychee-

      # - name: Check links
      #   uses: lycheeverse/lychee-action@v2
      #   with:
      #     args: "--cache --max-cache-age 1d ."
      #     fail: true
