name: Publish artifacts with ORAS

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  publish-aa-and-initdata-validator:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        platform: [
          { tee: none,        arch: x86_64,  libc: musl, runner: ubuntu-24.04 },
          { tee: none,        arch: s390x,   libc: gnu, runner: ubuntu-24.04-s390x },
          { tee: none,        arch: aarch64, libc: gnu, runner: ubuntu-24.04 },
          { tee: amd,         arch: x86_64,  libc: musl, runner: ubuntu-24.04 },
          { tee: az-cvm-vtpm, arch: x86_64,  libc: gnu, runner: ubuntu-24.04 },
          { tee: tdx,         arch: x86_64,  libc: musl, runner: ubuntu-24.04 },
          { tee: cca,         arch: x86_64,  libc: musl, runner: ubuntu-24.04 },
          { tee: cca,         arch: aarch64, libc: gnu, runner: ubuntu-24.04 },
          { tee: se,          arch: s390x,   libc: gnu, runner: ubuntu-24.04-s390x },
          { tee: none,        arch: powerpc64le,  libc: gnu, runner: ubuntu-24.04-ppc64le },
        ]
    runs-on: ${{ matrix.platform.runner }}
    env:
      TEE_PLATFORM: ${{ matrix.platform.tee }}
      LIBC: ${{ matrix.platform.libc }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      RUST_TARGET: ${{ matrix.platform.arch }}-unknown-linux-${{ matrix.platform.libc }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit

    - name: Log in to the Container registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: oras-project/setup-oras@38de303aac69abb66f3e6255b7198bff35f323e3 # v2.0.0
      with:
        version: 1.2.0

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      with:
        target: ${{ env.RUST_TARGET }}

    - name: Update apt source list
      run: |
        sudo apt-get update

    - name: Install tpm dependencies
      if: matrix.platform.tee == 'az-cvm-vtpm'
      run: |
        sudo apt-get install -y --no-install-recommends libtss2-dev

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Build AA and Initdata Validator
      env:
        ARCH: ${{ matrix.platform.arch }}
        LIBC: ${{ matrix.platform.libc }}
      run: |
        make ./target/${{ env.RUST_TARGET }}/release/attestation-agent
        make ./target/${{ env.RUST_TARGET }}/release/initdata-validator

    - name: Publish AA with ORAS
      id: publish
      uses: ./.github/actions/publish-oras-artifact
      with:
        registry: ${{ env.REGISTRY }}
        image_name: ${{ env.IMAGE_NAME }}
        artifact_name: attestation-agent
        rust_target: ${{ env.RUST_TARGET }}
        git_sha: ${{ github.sha }}
        tee: ${{ matrix.platform.tee }}
        arch: ${{ matrix.platform.arch }}
        oci_arch: ${{ matrix.platform.arch == 'x86_64' && 'amd64' || matrix.platform.arch == 'aarch64' && 'arm64' || matrix.platform.arch == 'powerpc64le' && 'ppc64le' || matrix.platform.arch }}

    - name: Publish Initdata Validator with ORAS
      id: publish-initdata-validator
      uses: ./.github/actions/publish-oras-artifact
      with:
        registry: ${{ env.REGISTRY }}
        image_name: ${{ env.IMAGE_NAME }}
        artifact_name: initdata-validator
        rust_target: ${{ env.RUST_TARGET }}
        git_sha: ${{ github.sha }}
        tee: ${{ matrix.platform.tee }}
        arch: ${{ matrix.platform.arch }}
        oci_arch: ${{ matrix.platform.arch == 'x86_64' && 'amd64' || matrix.platform.arch == 'aarch64' && 'arm64' || matrix.platform.arch == 'powerpc64le' && 'ppc64le' || matrix.platform.arch }}

    - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
      with:
        subject-name: ${{ steps.publish.outputs.image }}
        subject-digest: ${{ steps.publish.outputs.digest }}
        push-to-registry: true

    - uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
      with:
        subject-name: ${{ steps.publish-initdata-validator.outputs.image }}
        subject-digest: ${{ steps.publish-initdata-validator.outputs.digest }}
        push-to-registry: true

  publish-cdh-and-asr:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        arch:
        - x86_64
        - s390x
        - aarch64
        - powerpc64le
        include:
        - arch: x86_64
          libc: musl
          instance: ubuntu-24.04
        - arch: s390x
          libc: gnu
          instance: ubuntu-24.04-s390x
        - arch: aarch64
          libc: gnu
          instance: ubuntu-24.04-arm
        - arch: powerpc64le
          libc: gnu
          instance: ubuntu-24.04-ppc64le
    runs-on: ${{ matrix.instance }}
    env:
      LIBC: ${{ matrix.libc }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      RUST_TARGET: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit

    - name: Log in to the Container registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: oras-project/setup-oras@38de303aac69abb66f3e6255b7198bff35f323e3 # v2.0.0
      with:
        version: 1.2.0

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      with:
        target: ${{ env.RUST_TARGET }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libdevmapper-dev pkg-config
        if [ "${{ matrix.arch }}" = "powerpc64le" ]; then
          sudo apt-get install -y libclang-dev cmake protobuf-compiler
        fi

    - name: Build CDH
      env:
        ARCH: ${{ matrix.arch }}
        LIBC: ${{ matrix.libc }}
      run: make ./target/${{ env.RUST_TARGET }}/release/confidential-data-hub

    - name: Build ASR
      env:
        ARCH: ${{ matrix.arch }}
        LIBC: ${{ matrix.libc }}
      run: make ./target/${{ env.RUST_TARGET }}/release/api-server-rest

    - name: Publish CDH + ASR with ORAS
      id: publish
      run: |
        arch="${{ matrix.arch }}"
        # After building for target powerpc64le, tag and push the image as ppc64le to match standard arch naming.
        [ "$arch" = "powerpc64le" ] && arch="ppc64le"
        tag="${{ github.sha }}-${arch}"
        mkdir oras
        cd oras
        cp ../target/${{ env.RUST_TARGET }}/release/{confidential-data-hub,api-server-rest} .

        tar cJf confidential-data-hub.tar.xz confidential-data-hub
        image="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/confidential-data-hub"
        oras push "${image}:${tag}" confidential-data-hub.tar.xz
        echo "cdh-image=${image}" >> "$GITHUB_OUTPUT"
        digest="$(oras manifest fetch "${image}:${tag}" --descriptor | jq -r .digest)"
        echo "cdh-digest=${digest}" >> "$GITHUB_OUTPUT"

        tar cJf api-server-rest.tar.xz api-server-rest
        image="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api-server-rest"
        oras push "${image}:${tag}" api-server-rest.tar.xz
        echo "asr-image=${image}" >> "$GITHUB_OUTPUT"
        digest="$(oras manifest fetch "${image}:${tag}" --descriptor | jq -r .digest)"
        echo "asr-digest=${digest}" >> "$GITHUB_OUTPUT"

    - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
      with:
        subject-name: ${{ steps.publish.outputs.cdh-image }}
        subject-digest: ${{ steps.publish.outputs.cdh-digest }}
        push-to-registry: true

    - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
      with:
        subject-name: ${{ steps.publish.outputs.asr-image }}
        subject-digest: ${{ steps.publish.outputs.asr-digest }}
        push-to-registry: true
